name = "TimerWheels"
uuid = "aebde43d-366d-4353-b020-04442e269197"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.2.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"

[targets]
test = ["Test", "Printf"]
