name = "TimerWheels"
uuid = "aebde43d-366d-4353-b020-04442e269197"
authors = ["Darryl Gamroth <dgamroth@rubus.ca>"]
version = "0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
